// Dummy data for demonstration

export const dummyNGOs = [
  {
    id: "1",
    name: "Akshaya Patra Foundation",
    category: "Education",
    location: "Bangalore, Karnataka",
    verified: true,
    rating: 4.9,
    totalRaised: 4500000,
    goal: 5000000,
    beneficiaries: 15000,
    description: "Providing mid-day meals to school children across India.",
    image: "https://images.unsplash.com/photo-1488521787991-ed7bbaae773c?w=400",
    aiMatchScore: 95,
  },
  {
    id: "2",
    name: "GiveIndia Healthcare",
    category: "Healthcare",
    location: "Mumbai, Maharashtra",
    verified: true,
    rating: 4.8,
    totalRaised: 3200000,
    goal: 4000000,
    beneficiaries: 8500,
    description: "Providing free healthcare to underprivileged communities.",
    image: "https://images.unsplash.com/photo-1576091160550-2173dba999ef?w=400",
    aiMatchScore: 88,
  },
  {
    id: "3",
    name: "Green Earth Initiative",
    category: "Environment",
    location: "Delhi, NCR",
    verified: true,
    rating: 4.7,
    totalRaised: 1800000,
    goal: 2500000,
    beneficiaries: 25000,
    description: "Planting trees and promoting sustainable living practices.",
    image: "https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?w=400",
    aiMatchScore: 82,
  },
  {
    id: "4",
    name: "Pratham Education",
    category: "Education",
    location: "Pune, Maharashtra",
    verified: true,
    rating: 4.9,
    totalRaised: 6200000,
    goal: 7000000,
    beneficiaries: 45000,
    description: "Improving quality of education for children in rural areas.",
    image: "https://images.unsplash.com/photo-1503676260728-1c00da094a0b?w=400",
    aiMatchScore: 91,
  },
  {
    id: "5",
    name: "Smile Foundation",
    category: "Child Welfare",
    location: "Chennai, Tamil Nadu",
    verified: true,
    rating: 4.6,
    totalRaised: 2100000,
    goal: 3000000,
    beneficiaries: 12000,
    description: "Empowering underprivileged children through education and healthcare.",
    image: "https://images.unsplash.com/photo-1488521787991-ed7bbaae773c?w=400",
    aiMatchScore: 79,
  },
];

export const dummyDonations = [
  {
    id: "d1",
    ngoName: "Akshaya Patra Foundation",
    amount: 5000,
    date: "2024-01-15",
    status: "completed",
    impact: "Provided meals to 50 children for a month",
    receiptId: "TAX-2024-001",
  },
  {
    id: "d2",
    ngoName: "GiveIndia Healthcare",
    amount: 10000,
    date: "2024-01-10",
    status: "completed",
    impact: "Funded 5 medical checkups",
    receiptId: "TAX-2024-002",
  },
  {
    id: "d3",
    ngoName: "Green Earth Initiative",
    amount: 2500,
    date: "2024-01-05",
    status: "completed",
    impact: "Planted 25 trees",
    receiptId: "TAX-2024-003",
  },
  {
    id: "d4",
    ngoName: "Pratham Education",
    amount: 7500,
    date: "2023-12-20",
    status: "completed",
    impact: "Provided books to 15 students",
    receiptId: "TAX-2023-045",
  },
];

export const dummyDonorProfile = {
  id: "donor1",
  name: "Rahul Sharma",
  email: "rahul@example.com",
  phone: "+91 98765 43210",
  totalDonated: 25000,
  donationsCount: 4,
  causes: ["Education", "Healthcare"],
  memberSince: "2023-06-15",
  impactScore: 850,
  livesImpacted: 95,
  taxSaved: 6250,
};

export const dummyNGOProfile = {
  id: "ngo1",
  name: "Hope Foundation",
  email: "contact@hopefoundation.org",
  phone: "+91 98765 12345",
  category: "Education",
  location: "Bangalore, Karnataka",
  verified: true,
  totalRaised: 1250000,
  donorsCount: 245,
  activeCampaigns: 3,
  beneficiaries: 3500,
  memberSince: "2022-03-10",
  rating: 4.8,
};

export const dummyNGODonations = [
  {
    id: "nd1",
    donorName: "Anonymous",
    amount: 15000,
    date: "2024-01-18",
    campaign: "School Supplies Drive",
  },
  {
    id: "nd2",
    donorName: "Priya M.",
    amount: 5000,
    date: "2024-01-17",
    campaign: "Teacher Training Program",
  },
  {
    id: "nd3",
    donorName: "Corporate Donor",
    amount: 50000,
    date: "2024-01-15",
    campaign: "Infrastructure Development",
  },
  {
    id: "nd4",
    donorName: "Amit K.",
    amount: 2500,
    date: "2024-01-14",
    campaign: "School Supplies Drive",
  },
];

export const aiChatMessages = [
  {
    role: "assistant" as const,
    content: "Hello! I'm your AI giving assistant. I can help you find the perfect NGOs that match your interests. What causes are you passionate about?",
  },
];

export const causeCategories = [
  "Education",
  "Healthcare",
  "Environment",
  "Child Welfare",
  "Women Empowerment",
  "Animal Welfare",
  "Disaster Relief",
  "Elderly Care",
];
